/**
 * Accord Project Integration (Simplified)
 *
 * AI-first approach using Concerto for validation only.
 * Contracts are generated by AI and validated against Concerto models.
 */

export {
  validateAgreementData,
  validateField,
  validateWalletAddress,
  validateEmail,
  getRequiredFields,
  getSampleData,
  getModelForType,
  getClassNameForType,
  createModelManager,
  type AgreementType,
  type ValidationResult,
} from "./validation";
